name: Docker Image CI

on:
  push:
    branches: [ master, test ]
  pull_request:
    branches: [ master, test ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
